### ISSUE TITLE
3.3.1/3.3.2 Seem to be Causing 4-Hour Rewinds After Connectivity Issues

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#66] opened 2015-07-29 16:37 UTC
On Monday, while pulling listening data for the iPhone app, I noticed that duration delivered spiked at the end of June, without a corresponding rise in session counts or unique IPs.

It appears that this jump corresponds with huge increase in the number of `attemptToFixLargeGapInStream` events being sent to Mixpanel.

Looking at data this morning, 120 sessions were ~4hours rewound in the 7am hour, so I think this must be affecting a fair number of listeners.

I've posted a bunch more graphs into #audio-ops, and have a few listener IDs that can illustrate the issue.

**Comment by vsinghkpcc** [comment] 2015-08-06 17:44
(TIMEBOXED)

AC

1) Determine cause / find STR

**Comment by benkpcc** [comment] 2015-08-13 22:01
As with the crash happening after forward seeks I still cannot reproduce this unfortunately. However, similarly I attempted to identify some potentially problematic areas around these conditions and modify the behavior with hopes we can float this out to production and then we see a reduction or complete end to the rewound listening spikes generated by this problem. Fix has been deployed and shipped with build 127 which is our 3.3.5 release candidate.

**Closed** 2015-08-17 21:59 UTC
