### ISSUE TITLE
Investigate Issues with Pausing the Live Stream

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#224] opened 2016-06-30 22:11 UTC
AC
- [ ] ~~Understand what is causing the live stream to go to live after unpausing~~
- [x] Pose possible solution(s)

**Comment by chris-fuller** [comment] 2016-07-08 01:03
I do not understand what the cause is. But I've added a commit to help mitigate this issue. Moving this to `Review` for now. We can revisit or reopen as necessary.

**Closed** 2016-07-08 18:50 UTC
Labels: dept-product
